### ISSUE TITLE
Hago un programa principal en el proyecto...

### ISSUE THREAD

**Issue by Autinfit** [Autinfit/Introducci-nACMasMas#1]
...dentro de un método ejecuté la aplicación, pero no salía nada de dónde aparecen los valores desplegados dentro de dicho método principal en el "main".

¿Me puedes ayudar, estimado MARSFOREVER472?

Gracias.

**Comment by MARSFOREVER472** [comment]
Por supuesto, estimado, es súper sencillo de hacer, sé que en el código que hiciste no detectaba ningún error de compilación, pero en el menú de herramientas de arriba del proyecto había una pestaña dónde decía depurar "Paso a paso por instrucciones", y luego yendo por líneas de código imprime los valores que tú depuraste.

Espero te sirva de ayuda, estimado!

Saludos.

**Comment by Autinfit** [comment]
Gracias, pero para ver los valores es por línea de código?

**Comment by MARSFOREVER472** [comment]
De lo que habías escrito mediante algoritmo preferencial, ya sea de manera algebraica, o más bien un número que contenga una variable.

**Comment by Autinfit** [comment]
Muchas gracias, ahí me fijé en ese detalle que se me escapó!

Saludos, estimado!
